### ISSUE TITLE
Volk (master) failed to build on CentOS 6.4 / 6.5 / 6.6 

### ISSUE THREAD

**Issue by sgardner340** [gnuradio/volk#45] opened 2015-09-01 14:28 UTC
21:35:41 Current step: (volk :: make)
21:35:41 make
21:35:41 bashexec (/home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/rpm-src/src/volk/build):: 
21:35:41     find . -name '_.make' -print0 | xargs -0 sed -i 's/(^._)(--cyan \")(._)\"$/\1\2\x1b[36;1m\3\x1b[0m\"/;s/(^._)(--green \")(._)\"$/\1\2\x1b[32;1m\3\x1b[0m\"/;s/(^._)(--red --bold \")(._)\"$/\1\2\x1b[31;1m\3\x1b[0m\"/;s/(^._)(--blue --bold \")(._)\"$/\1\2\x1b[34;1m\3\x1b[0m\"/'
21:35:41     find . -name 'Makefile' -print0 | xargs -0 sed -i 's/(^._)(--cyan \")(._)\"$/\1\2\x1b[36;1m\3\x1b[0m\"/;s/(^._)(--green \")(._)\"$/\1\2\x1b[32;1m\3\x1b[0m\"/;s/(^._)(--red --bold \")(._)\"$/\1\2\x1b[31;1m\3\x1b[0m\"/;s/(^._)(--blue --bold \")(._)\"$/\1\2\x1b[34;1m\3\x1b[0m\"/'
21:35:41     ln -s /home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/rpm-src/colorgcc.pl /apps/smokey64/bin/cc
21:35:41     ln -s /home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/rpm-src/colorgcc.pl /apps/smokey64/bin/gcc
21:35:41     ln -s /home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/rpm-src/colorgcc.pl /apps/smokey64/bin/c++
21:35:41     ln -s /home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/rpm-src/colorgcc.pl /apps/smokey64/bin/g++
21:35:41     make -j4
21:35:41 
21:35:41 Scanning dependencies of target pygen_python_volk_modtool_1a4b4
21:35:41 [  2%] [  5%] [  7%] Scanning dependencies of target pygen_python_volk_modtool_760e7
21:35:41 Shebangin volk_modtool
21:35:41 Generating ../include/volk/volk.h
21:35:41 [ 10%] Generating volk_machine_avx_64_mmx.c
21:35:41 Generating **init**.pyc, cfg.pyc, volk_modtool_generate.pyc
21:35:41 [ 10%] Built target pygen_python_volk_modtool_1a4b4
21:35:41 [ 12%] Generating **init**.pyo, cfg.pyo, volk_modtool_generate.pyo
21:35:41 [ 12%] Built target pygen_python_volk_modtool_760e7
21:35:41 [ 15%] [ 17%] Generating volk.c
21:35:41 Generating ../include/volk/volk_typedefs.h
21:35:42 /apps/smokey64/lib64/python2.6/site-packages/Cheetah/CacheRegion.py:30: DeprecationWarning: the md5 module is deprecated; use hashlib instead
21:35:42   import md5
21:35:42 /apps/smokey64/lib64/python2.6/site-packages/Cheetah/CacheRegion.py:30: DeprecationWarning: the md5 module is deprecated; use hashlib instead
21:35:42   import md5
21:35:42 /apps/smokey64/lib64/python2.6/site-packages/Cheetah/CacheRegion.py:30: DeprecationWarning: the md5 module is deprecated; use hashlib instead
21:35:42   import md5
21:35:42 [ 20%] Generating ../include/volk/volk_cpu.h
21:35:42 [ 23%] Generating volk_cpu.c
21:35:42 [ 25%] Generating ../include/volk/volk_config_fixed.h
21:35:42 /apps/smokey64/lib64/python2.6/site-packages/Cheetah/CacheRegion.py:30: DeprecationWarning: the md5 module is deprecated; use hashlib instead
21:35:42   import md5
21:35:42 [ 28%] Generating volk_machines.h
21:35:42 /apps/smokey64/lib64/python2.6/site-packages/Cheetah/CacheRegion.py:30: DeprecationWarning: the md5 module is deprecated; use hashlib instead
21:35:42   import md5
21:35:42 [ 30%] Generating volk_machines.c
21:35:42 /apps/smokey64/lib64/python2.6/site-packages/Cheetah/CacheRegion.py:30: DeprecationWarning: the md5 module is deprecated; use hashlib instead
21:35:42   import md5
21:35:42 [ 33%] /apps/smokey64/lib64/python2.6/site-packages/Cheetah/CacheRegion.py:30: DeprecationWarning: the md5 module is deprecated; use hashlib instead
21:35:42   import md5
21:35:42 Generating volk_machine_generic.c
21:35:42 [ 35%] Generating volk_machine_sse2_64_mmx.c
21:35:43 /apps/smokey64/lib64/python2.6/site-packages/Cheetah/CacheRegion.py:30: DeprecationWarning: the md5 module is deprecated; use hashlib instead
21:35:43   import md5
21:35:43 /apps/smokey64/lib64/python2.6/site-packages/Cheetah/CacheRegion.py:30: DeprecationWarning: the md5 module is deprecated; use hashlib instead
21:35:43   import md5
21:35:43 /apps/smokey64/lib64/python2.6/site-packages/Cheetah/CacheRegion.py:30: DeprecationWarning: the md5 module is deprecated; use hashlib instead
21:35:43   import md5
21:35:43 [ 38%] Generating volk_machine_sse3_64.c
21:35:43 [ 41%] Generating volk_machine_ssse3_64.c
21:35:43 [ 43%] Generating volk_machine_sse4_a_64.c
21:35:43 /apps/smokey64/lib64/python2.6/site-packages/Cheetah/CacheRegion.py:30: DeprecationWarning: the md5 module is deprecated; use hashlib instead
21:35:43   import md5
21:35:43 [ 46%] Generating volk_machine_sse4_1_64.c
21:35:43 /apps/smokey64/lib64/python2.6/site-packages/Cheetah/CacheRegion.py:30: DeprecationWarning: the md5 module is deprecated; use hashlib instead
21:35:43   import md5
21:35:43 /apps/smokey64/lib64/python2.6/site-packages/Cheetah/CacheRegion.py:30: DeprecationWarning: the md5 module is deprecated; use hashlib instead
21:35:43   import md5
21:35:43 [ 48%] Generating volk_machine_sse4_2_64.c
21:35:43 /apps/smokey64/lib64/python2.6/site-packages/Cheetah/CacheRegion.py:30: DeprecationWarning: the md5 module is deprecated; use hashlib instead
21:35:43   import md5
21:35:43 /apps/smokey64/lib64/python2.6/site-packages/Cheetah/CacheRegion.py:30: DeprecationWarning: the md5 module is deprecated; use hashlib instead
21:35:43   import md5
21:35:44 /apps/smokey64/lib64/python2.6/site-packages/Cheetah/CacheRegion.py:30: DeprecationWarning: the md5 module is deprecated; use hashlib instead
21:35:44   import md5
21:35:44 Scanning dependencies of target volk_obj
21:35:44 [ 51%] [ 53%] [ 56%] [ 58%] Building C object lib/CMakeFiles/volk_obj.dir/constants.c.o
21:35:44 Building C object lib/CMakeFiles/volk_obj.dir/volk_prefs.c.o
21:35:44 Building C object lib/CMakeFiles/volk_obj.dir/volk_malloc.c.o
21:35:44 Building C object lib/CMakeFiles/volk_obj.dir/volk_rank_archs.c.o
21:35:44 [ 61%] Building C object lib/CMakeFiles/volk_obj.dir/volk.c.o
21:35:44 [ 64%] [ 66%] Building C object lib/CMakeFiles/volk_obj.dir/volk_cpu.c.o
21:35:44 Building C object lib/CMakeFiles/volk_obj.dir/volk_machines.c.o
21:35:44 [ 69%] Building C object lib/CMakeFiles/volk_obj.dir/volk_machine_generic.c.o
21:35:44 [ 71%] Building C object lib/CMakeFiles/volk_obj.dir/volk_machine_sse2_64_mmx.c.o
21:35:44 [ 74%] Building C object lib/CMakeFiles/volk_obj.dir/volk_machine_sse3_64.c.o
21:35:45 [ 76%] Building C object lib/CMakeFiles/volk_obj.dir/volk_machine_ssse3_64.c.o
21:35:45 In file included from /home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/rpm-src/src/volk/kernels/volk/volk_32f_8u_polarbutterfly_32f.h:74,:
21:35:45                  from /home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/rpm-src/src/volk/build/lib/volk_machine_ssse3_64.c:101:
21:35:45 /home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/rpm-src/src/volk/kernels/volk/volk_8u_x2_encodeframepolar_8u.h: In function ‘volk_8u_x2_encodeframepolar_8u_u_ssse3’:
21:35:45 /home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/rpm-src/src/volk/kernels/volk/volk_8u_x2_encodeframepolar_8u.h:124: warning: implicit declaration of function ‘_mm_bsrli_si128’
21:35:45 /home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/rpm-src/src/volk/kernels/volk/volk_8u_x2_encodeframepolar_8u.h:124: error: incompatible types when assigning to type ‘__m128i’ from type ‘int’
21:35:45 /home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/rpm-src/src/volk/kernels/volk/volk_8u_x2_encodeframepolar_8u.h:129: error: incompatible types when assigning to type ‘__m128i’ from type ‘int’
21:35:45 /home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/rpm-src/src/volk/kernels/volk/volk_8u_x2_encodeframepolar_8u.h:173: error: incompatible types when assigning to type ‘__m128i’ from type ‘int’
21:35:45 /home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/rpm-src/src/volk/kernels/volk/volk_8u_x2_encodeframepolar_8u.h:181: error: incompatible types when assigning to type ‘__m128i’ from type ‘int’
21:35:45 /home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/rpm-src/src/volk/kernels/volk/volk_8u_x2_encodeframepolar_8u.h:185: error: incompatible types when assigning to type ‘__m128i’ from type ‘int’
21:35:45 /home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/rpm-src/src/volk/kernels/volk/volk_8u_x2_encodeframepolar_8u.h:189: error: incompatible types when assigning to type ‘__m128i’ from type ‘int’
21:35:45 /home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/rpm-src/src/volk/kernels/volk/volk_8u_x2_encodeframepolar_8u.h: In function ‘volk_8u_x2_encodeframepolar_8u_a_ssse3’:
21:35:45 /home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/rpm-src/src/volk/kernels/volk/volk_8u_x2_encodeframepolar_8u.h:246: error: incompatible types when assigning to type ‘__m128i’ from type ‘int’
21:35:45 /home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/rpm-src/src/volk/kernels/volk/volk_8u_x2_encodeframepolar_8u.h:251: error: incompatible types when assigning to type ‘__m128i’ from type ‘int’
21:35:45 /home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/rpm-src/src/volk/kernels/volk/volk_8u_x2_encodeframepolar_8u.h:295: error: incompatible types when assigning to type ‘__m128i’ from type ‘int’
21:35:45 /home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/rpm-src/src/volk/kernels/volk/volk_8u_x2_encodeframepolar_8u.h:303: error: incompatible types when assigning to type ‘__m128i’ from type ‘int’
21:35:45 /home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/rpm-src/src/volk/kernels/volk/volk_8u_x2_encodeframepolar_8u.h:307: error: incompatible types when assigning to type ‘__m128i’ from type ‘int’
21:35:45 /home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/rpm-src/src/volk/kernels/volk/volk_8u_x2_encodeframepolar_8u.h:311: error: incompatible types when assigning to type ‘__m128i’ from type ‘int’
21:35:45 make[2]: *_\* [lib/CMakeFiles/volk_obj.dir/volk_machine_ssse3_64.c.o] Error 1
21:35:45 make[2]: **\* Waiting for unfinished jobs....
21:35:47 make[1]: **\* [lib/CMakeFiles/volk_obj.dir/all] Error 2
21:35:47 make: **\* [all] Error 2
21:35:47 bash return val = 2
21:35:47 Traceback (most recent call last):
21:35:47   File "./pybombs", line 360, in <module>
21:35:47     main()
21:35:47   File "./pybombs", line 357, in main
21:35:47     sys.exit(cli(parser,opts,args))
21:35:47   File "./pybombs", line 171, in cli
21:35:47     pybombs_ops.install(p, not opts.force);
21:35:47   File "/home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/rpm-src/mod_pybombs/pybombs_ops.py", line 151, in install
21:35:47     global_recipes[pkg].install();
21:35:47   File "/home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/rpm-src/mod_pybombs/recipe.py", line 531, in install
21:35:47     st = self.install_src();
21:35:47   File "/home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/rpm-src/mod_pybombs/recipe.py", line 598, in install_src
21:35:47     self.install_order[step][1]();
21:35:47   File "/home/hudson/workspace/PyBombs_Build_All_Matrix/os/CentOS_6.5_Desktop_x86_VM_R/satisfy_order/rpm-src/mod_pybombs/recipe.py", line 658, in make
21:35:47     assert(st == 0);
21:35:47 AssertionError
21:35:47 Build step 'Execute shell' marked build as failure
21:35:47 [WARNINGS] Skipping publisher since build result is FAILURE
21:35:47 Email was triggered for: Still Failing
21:35:47 Trigger Failure was overridden by another trigger and will not send an email.
21:35:47 Sending email for trigger: Still Failing

**Comment by n-west** [comment] 2015-09-01 15:42
Thanks for the report. In the future please paste make output with only 1 job so it's easier to read. This appears to be a duplicate of #44. Can you tell me your compiler version(s)?

**Comment by sgardner340** [comment] 2015-09-01 15:53
CentOS 6.4: gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)
CentOS 6.5: gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)
CentOS 6.6: gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)

On Tue, Sep 1, 2015 at 11:42 AM, Nathan West notifications@github.com
wrote:

> Thanks for the report. In the future please paste make output with only 1
> job so it's easier to read. This appears to be a duplicate of #44
> https://github.com/gnuradio/volk/issues/44. Can you tell me your
> compiler version(s)?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gnuradio/volk/issues/45#issuecomment-136765055.

## 

Steven Gardner
All good men know the power of prayer...

**Comment by n-west** [comment] 2015-10-06 18:45
Should be fixed now. Holler if it's not.

**Closed as completed by n-west** 2015-10-06 18:45 UTC

**Comment by sgardner340** [comment] 2015-10-07 00:30
Volk master works fine for me​

On Tue, Oct 6, 2015 at 2:45 PM, Nathan West notifications@github.com
wrote:

> Should be fixed now. Holler if it's not.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gnuradio/volk/issues/45#issuecomment-145960868.

## 

Steven Gardner
All good men know the power of prayer...
