### ISSUE TITLE
build issues with c++98 and gcc4 (libboost1.58 with c++11 style symbols)

### ISSUE THREAD

**Issue by osh** [gnuradio/volk#92] opened 2016-06-06 16:12 UTC
When building with gcc-4.x 
it is forced into c++98 mode resulting in undefined c++11 style ABI symbols not found when linking against libboost built for c++11.   Using gcc-5.x fixes the issue ... 
however 
by propperly setting 
_GLIBCXX_USE_CXX11_ABI 
somewhere, this should be fixable 
results in a non-helpful error message about simply missing symbols when linking the first binary (volk_profile)

C++11 Dual-ABI Info:
https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

**Comment by n-west** [comment] 2016-06-15 21:39
woah. What system/distro is this easily reproducible on?

**Comment by n-west** [comment] 2016-06-30 14:55
@tim is this still a thing?

**Comment by osh** [comment] 2016-06-30 16:00
yes, mixing 
-D_GLIBCXX_USE_CXX11_ABI=0 (gcc 4 default)
with
-D_GLIBCXX_USE_CXX11_ABI=1 (gcc 5 default) (how ubuntu boost is built now)
does bad things
since they have renamed the symbol for string, virtually no calls are left unmangled
std::string  -->   std::__cxx11::string

**Comment by n-west** [comment] 2016-07-02 16:08
I think this is fixed just before I tagged 1.3 release, but cannot reproduce

**Comment by n-west** [comment] 2016-07-13 21:28
I am now running in to this issue and my added define doesn't fix it. Have you gotten this to work? I'm not sure it's as simple as adding the define.

https://lwn.net/Articles/632658/

I'm thinking that BOOST should have been built with this flag set to 0 until Ubuntu completely removes support for gcc 4, which makes this somewhat of a packaging bug.

**Comment by n-west** [comment] 2016-07-13 22:15
This cannot be fixed in VOLK. We simply cannot link against a boost with CXX11 ABI.

**Closed as completed by n-west** 2016-07-13 22:15 UTC
